FROM nginx

# Part 3 - rate limiting

COPY nginx/rate-limitting.conf /etc/nginx/rate-limiting.conf

# Part1 - wstępna konfig

COPY certs/ /etc/nginx/ 

COPY nginx/ssl.conf /etc/nginx/ssl.conf

COPY nginx/locations.conf /etc/nginx/locations.conf

COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Part2 - certyfikaty klienckie

RUN mkdir /etc/nginx/client_certs

COPY clients.crt  /etc/nginx/client_certs/clients.crt

EXPOSE 80

EXPOSE 443