FROM nginx

# Part1 - wstępna konfig

COPY certs/ /etc/nginx/ 

COPY nginx/ssl.conf /etc/nginx/ssl.conf

COPY nginx/locations.conf /etc/nginx/locations.conf

COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Part2 - certyfikaty klienckie

RUN mkdir /etc/nginx/client_certs

COPY certs_users/User_A.crt certs_users/User_B.crt /etc/nginx/client_certs/

RUN cat /etc/nginx/server.crt /etc/nginx/client_certs/*.crt > /etc/nginx/client_certs/clients.crt

EXPOSE 80

EXPOSE 443