FROM httpd

#Part1 - wstępna konfig

COPY certs/ /usr/local/apache2/conf/

COPY apache/httpd.conf /usr/local/apache2/conf/httpd.conf

COPY apache/httpd-http.conf /usr/local/apache2/conf/extra/httpd-http.conf

COPY apache/httpd-ssl.conf /usr/local/apache2/conf/extra/httpd-ssl.conf

#Part2 - certyfikaty klienckie

RUN mkdir /usr/local/apache2/conf/client_certs

COPY certs/clients.crt /usr/local/apache2/conf/client_certs/clients.crt

EXPOSE 80

EXPOSE 443