FROM httpd

COPY certs/ /usr/local/apache2/conf/

COPY apache/httpd.conf /usr/local/apache2/conf/httpd.conf

COPY apache/httpd-http.conf /usr/local/apache2/conf/extra/httpd-http.conf

COPY apache/httpd-ssl.conf /usr/local/apache2/conf/extra/httpd-ssl.conf

EXPOSE 80

EXPOSE 443